### ISSUE TITLE
Add lowcost Bike mount

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/UserGuide#1]
Feel free to use this Photo in the wiki:

You can use a pipe insulation to make a low cost bike mount. This [Blog](http://www.bodenseepeter.de/2014/07/01/how-to-street-view-a-bike-path-for-a-penny/) inspired HolgerJeromin to make a simpler version. You just need the insulation and four cable ties.
![bikemapillarypipeinsulationwithphone](https://cloud.githubusercontent.com/assets/2410353/8041311/98809f7c-0e17-11e5-8c3f-dc094bed8683.jpg)

**Comment by HolgerJeromin** [comment]
@travel193 have you seen this? :-)

**Comment by travel193** [comment]
Hi @HolgerJeromin ,
Thanks for the photo and link to the blog.
I did see this and added it to [our list of recommended mounts](https://github.com/mapillary/UserGuide/wiki/Equipment-&-Mounts). I'll give it more of a mention today and add the photo.

**Comment by HolgerJeromin** [comment]
Peter Eich mount is quite different to mine. Thats why i wrote
"You can use a pipe insulation to make a low cost bike mount. This Blog inspired HolgerJeromin to make a **simpler version**. You just need the insulation and four cable ties.

**Comment by travel193** [comment]
Hi @HolgerJeromin ,
You

**Comment by HolgerJeromin** [comment]
Peter did two things. A card board envelope holder which he put into the insulation thing. I build both, but used only the insulation thing on my bike. 
I think my photo with Peters blog is enough to rebuild it.
I use the envelope thing with my car (will post photos from that later).

"You can use a pipe insulation to make a low cost bike mount. This Blog inspired HolgerJeromin to make a simpler version. You just need the insulation and four cable ties." was meant as a copy and paste suggestion for the wiki :-)

**Comment by travel193** [comment]
Awesome. 
Thanks @HolgerJeromin 

Share your photo here for you car set up when you can :)

**Comment by HolgerJeromin** [comment]
Thanks. 

Will do that.
