### ISSUE TITLE
Filter bug on mapillary.com 

### ISSUE THREAD

**Issue by madelenarnesdotter** [mapillary/UserGuide#10]
<img width="1227" alt="screen shot 2016-09-20 at 17 20 10" src="https://cloud.githubusercontent.com/assets/6813969/18689350/ade4d8c2-7f56-11e6-809b-395788b40e32.png">
I searched for this user (username: avikdor) because I wanted to review a sequence for him.

<img width="1231" alt="screen shot 2016-09-20 at 17 20 38" src="https://cloud.githubusercontent.com/assets/6813969/18689351/adef2b42-7f56-11e6-9ab0-a7ad0b367f73.png">
When I open up the view, the sequence is from another user (username: wowik).

**Comment by gyllen** [comment]
@madelenarnesdotter You should report this issue in https://github.com/mapillary/mapillary_elva/issues since its a front-end issue
