### ISSUE TITLE
Add lowcost Car mount

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/UserGuide#3]
Follow up to #1 

The cardboard from Peters blog post was used by Holger for his car! The car has a sun visor with a strip for papers or something like that. The cardboard got an extension, so it slips easy under the visor strip from the right side. The amount of sky/street in the view can be easily adjusted by rotating the visor. The left/right direction is quite fix (without loosing stability).

![mapillarycar](https://cloud.githubusercontent.com/assets/2410353/8651872/caf13e24-297b-11e5-83e4-28aa737ec738.jpg)

**Comment by travel193** [comment]
Added to the user guide. Thanks for the DIY tip.
