### ISSUE TITLE
Software Resets Occasionally While Taking Photos In Riding-Mode

### ISSUE THREAD

**Issue by PaulColinSimpson** [mapillary/UserGuide#7]
I noticed on the latest version of the Mapillary app that the app resetted on a number of occasions while using it in the car in Riding-mode. Additional information:
- Used in Riding mode.
- Mobile phone- iPhone 6....iOS 9.3.1.
- Capture Interval set to default (1s).
- Mobile phone was plugged into main charger in the vehicle while in use.

**Comment by richlv** [comment]
this issue seems to be in the wrong repository, should have went into https://github.com/mapillary/mapillary_issues/issues

**Comment by travel193** [comment]
Closing this issue @PaulColinSimpson as it should have been fixed in a subsequent release. If it reappears, most the details into: [https://github.com/mapillary/mapillary_issues/issues](https://github.com/mapillary/mapillary_issues/issues)
